name: buah_seru
description: "Buah-Seru: kenali apel, jeruk, dan pisang dengan model CNN di perangkat, lalu belajar lewat kuis dan info gizi."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  image_picker: ^1.2.4
  tflite_flutter: ^0.12.1
  image: ^4.10.1
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/model/
    - assets/samples/
    - assets/logo_buah_seru.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
